# Book settings
title: Data Quality Explored
author: STS
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

html:
  navbar_number_sections: false

launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : true  # Add a thebe button to pages (requires the repository to run on Binder)

# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : | 
    <div>
    <p><a href="https://www.tuhh.de/alt/tuhh/about-us/imprint.html" target="_blank" style="font-weight:bold;color:#5a5a5a">Imprint of TUHH</a></p> 
    <p>Funded by</p> 
    <a href="https://www.hoou.de/" target="_blank"><img src="_images/hoou_logo.png" width="150px"></a> 
    </div>
    <div style="margin-top:50px">
    <p>Powered by <a href="https://jupyterbook.org" target="_blank">Jupyter Book</a> </p>
    </div> # Will be displayed underneath the left navbar.

  extra_footer              : <div> 
                              <p><a href="https://www.tuhh.de/alt/tuhh/about-us/imprint.html" target="_blank" style="font-weight:bold;color:#333333">Imprint of TUHH</a></p> 
                              <p>Funded by <a href="https://www.hoou.de/" target="_blank"><img src="_images/hoou_logo.png" width="150px" style="margin-left:10px"></a> 
                              </div> # Will be displayed underneath the footer.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/

repository:
  url                       : https://github.com/annalaine/quaxp  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : development  # Which branch of the repository should be used when creating links

parse:
  myst_extended_syntax      : true